# Generated by Django 5.0.6 on 2026-08-02 04:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_category_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='product',
            name='available_quantity_for_booking',
            field=models.PositiveIntegerField(default=1, help_text='Number of units available for booking'),
        ),
        migrations.AddField(
            model_name='product',
            name='booking_price_per_day',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price per day for booking', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_bookable',
            field=models.BooleanField(default=False, help_text='Enable booking for this product'),
        ),
        migrations.AddField(
            model_name='product',
            name='max_booking_days',
            field=models.PositiveIntegerField(default=30, help_text='Maximum days allowed for booking'),
        ),
        migrations.AddField(
            model_name='product',
            name='min_booking_days',
            field=models.PositiveIntegerField(default=1, help_text='Minimum days required for booking'),
        ),
        migrations.AddField(
            model_name='product',
            name='wishlist_count',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Number of users who added this to wishlist'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
